### ISSUE TITLE
Referecing issue #188: Will multi-GPU speed up DistributedD4PG?

### ISSUE THREAD

**Issue by templarares** [deepmind/acme#190] opened 2022-01-08 04:28 UTC
Ah, I thought you are asking about using multi-GPU setup for speeding up the _learner_. The trick I mentioned above will help with the learner, not with experience collection.

Actors currently are setup to run NN inference on CPU. Changing the backend [here](https://github.com/deepmind/acme/blob/67ee5c80dfdc1e5ac1f973163e4d96928d52b567/acme/agents/jax/d4pg/builder.py#L201) _should_ be enough to make use of multiple GPUs for inference during experience collection. Note, however, that in many cases the bottleneck for experience collection is in running the environments (which are more often CPU-bound than GPU-bound). In such cases running the networks on GPU won't help. We would usually run multiple actors on different machines in order to address this. Running several actors in different processes on the same machine might also help if the machine is powerful enough to efficiently run multiple instances of the environment.

I hope this sufficiently answers your question. I'll close the issue for now, but feel free to reopen if you have further questions.

_Originally posted by @nikolamomchev in https://github.com/deepmind/acme/issues/188#issuecomment-1007358536_

Hi nikolamomchev, 
Please excuse me for keep asking about this: You explained that actors are running NN on CPU, but they are using the GPU somewhere else, right? As each of my actor processes, created by Distributed D4PG via LaunchPad, consumes about 580MB of my RTX 2080's memory (after turning on the "memory_growth" option for my GPU in TF). So I can only run 10 actors in the same time on my host, as together with the learner and evaluator they will take most of my GPU's 8GB memory. In the same time my CPU usage is only 66% and memory usage below 50%. So I identified the performance bottleneck in my situation as the GPU. Thus I was wondering if simply adding another 2080 will help, without too much modification of the code, of course. Thanks again for your patience and responses!

**Comment by nikolamomchev** [comment] 2022-01-08 09:02
Let's reopen #188 and keep the discussion there.

**Comment by nikolamomchev** [comment] 2022-01-08 09:03
Duplicate of #188

**Closed by nikolamomchev** 2022-01-08 09:02 UTC

**Comment by templarares** [comment] 2022-01-08 09:10
> Let's reopen #188 and keep the discussion there.

Thing is, I cannot reopen #188... Per GitHub rules, I cannot reopen an issue unless it's created and CLOSED by myself.

**Comment by nikolamomchev** [comment] 2022-01-08 09:54
> > Let's reopen #188 and keep the discussion there.
> 
> Thing is, I cannot reopen #188... Per GitHub rules, I cannot reopen an issue unless it's created and CLOSED by myself.

Ah, I didn't realise this is the case, sorry. I've reopened it and sent you a reply there.
