### ISSUE TITLE
Cannot interrupt or kill the program due to signal handler

### ISSUE THREAD

**Issue by wookayin** [deepmind/acme#199] opened 2022-02-10 02:15 UTC
When acme's environment_loop is running (with some launchpad/reverb programming running as children processes), I cannot interrupt or kill the program. I am on a standard linux environment where the main python process is spawned from shell (bash/zsh) using commands like `python train.py`.

When pressing CTRL+C, I expect SIGINT signal works to interrupt the program (with some graceful handling of child processes as well). But what I see in the console is a bunch of `^C^C^C` -- the signal handler seems eating the signal.

I guess this is related to `acme/utils/signal.py`: https://github.com/deepmind/acme/blob/fbdc7b9b8d51f10b5c397fa7715b3b4f3a5d7000/acme/utils/signals.py#L28-L53. Any helps would be appreciated.

**Comment by qstanczyk** [comment] 2022-02-10 07:10
What is the version of Acme you are running? There were some changes recently for termination handling. Could you give v0.4.0 a try?

**Comment by wookayin** [comment] 2022-02-10 07:27
My working copy of acme was based on `d425a3c`, but I don't see any relevant changes in d425a3c..b81159b (0.4.0). I will give v0.4.0 a try tomorrow and let you know. FYI my agent was based on a LocalLayout (not distributed one), but I believe both will share the same problem.

**Comment by qstanczyk** [comment] 2022-02-10 07:38
LocalLayout doesn't use Launchpad and it doesn't support clean termination. Please give distributed layout a try. That should work fine.

**Comment by ethanluoyc** [comment] 2022-03-01 00:04
I can confirm what @wookayin says and have encountered a similar issue with local agent. The examples bc_jax agent cannot be interrupted for some reason. I am using dm-acme 0.4.0

**Comment by ethanluoyc** [comment] 2022-03-01 10:44
OK so after some bisecting, I think I have found the issue. 

The problem is in this line:

https://github.com/deepmind/launchpad/blob/14bd68213af87a2989149dcecb46a056195ee092/launchpad/launch/worker_manager.py#L64-L65

Looks like the keyboard interrupt is ignored with the try catch pass statements. Not sure why this is done here, but removing that or disable registering the SIGINT handler in 
https://github.com/deepmind/launchpad/blob/14bd68213af87a2989149dcecb46a056195ee092/launchpad/launch/worker_manager.py#L85
seems to solve the problem for me.

**Comment by qstanczyk** [comment] 2022-03-02 09:52
Thanks for investigating this problem. Fix is under development.

**Comment by qstanczyk** [comment] 2022-03-03 10:29
Fix is in - changes are both on Acme and Launchpad side - could you give it a try installing Acme / Launchpad from head (not PyPi)?

**Comment by ethanluoyc** [comment] 2022-03-03 16:53
I don't have a local setup for building launchpad so I suppose I can try it out once the change is in nightly.

**Comment by ethanluoyc** [comment] 2022-03-04 14:00
@qstanczyk Thanks a lot for the fix. This appears to be working for me.

I hope this can be made into the released version soon. Out of curiosity, how are you managing the release process of Acme?

**Comment by qstanczyk** [comment] 2022-05-23 12:32
Please reopen if there are any further questions on the topic.

**Closed by qstanczyk** 2022-05-23 12:32 UTC
