### ISSUE TITLE
GymWrapper: deepcopy fails due to its __getattr__ method

### ISSUE THREAD

**Issue by graidl** [deepmind/acme#31] opened 2020-06-19 10:35 UTC
MCTS needs to deepcopy the environment. When used with a Gym environment wrapped with `GymWrapper`, deepcopy fails with an infinite recursion due to `GymWrapper`'s `__getattr__` method.

I tried to resolve the problem by an own `__deepcopy__` method in my Gym environment, but this also did not work as then only my Gym environment without the wrapper is copied.

Commenting out `GymWrapper.__getattr__` resolves the problem in my case, but this is clearly not what was originally intended.

**Comment by qstanczyk** [comment] 2021-12-06 07:56
This should be fixed at head now.

**Comment by ahalev** [comment] 2021-12-10 00:33
I am also having this issue, with gym 0.21.0. Is there a fix available in a different version?

**Comment by qstanczyk** [comment] 2021-12-10 06:54
Can you share a minimal repro of the problem?

**Comment by ahalev** [comment] 2021-12-10 17:15
So I determined the issue, although I still think this behavior is suboptimal.

The problem is that I was using a wrapper like this 

```python
import gym
class BadWrapper(gym.Wrapper):
    def __getattr__(self, name):
        return getattr(self.env, name)
```
in order to be able to access protected variables of an environment if necessary. But this doesn't work when you deepcopy; you end up in an infinite recursion because `__getattr__` continuously calls itself:

```python
bad_wrapped_env = BadWrapper(gym.make('Pong-v0')) 
bad_copied_env = deepcopy(bad_wrapped_env) # This doesn't work
```
which raises
```
Traceback (most recent call last):
  File "/home/ahalev/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ahalev/mgrid/dev/garage_sandbox/wrapper_ex.py", line 17, in <module>
    bad_copied_env = deepcopy(bad_wrapped_env)
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/copy.py", line 281, in _reconstruct
    if hasattr(y, '__setstate__'):
  File "/home/ahalev/mgrid/dev/garage_sandbox/wrapper_ex.py", line 10, in __getattr__
    return getattr(self.env, name)
  File "/home/ahalev/mgrid/dev/garage_sandbox/wrapper_ex.py", line 10, in __getattr__
    return getattr(self.env, name)
  File "/home/ahalev/mgrid/dev/garage_sandbox/wrapper_ex.py", line 10, in __getattr__
    return getattr(self.env, name)
  [Previous line repeated 992 more times]
  File "/home/ahalev/mgrid/dev/garage_sandbox/wrapper_ex.py", line 5, in __getattr__
    def __getattr__(self, name):
RecursionError: maximum recursion depth exceeded
python-BaseException
Traceback (most recent call last):
  File "/home/ahalev/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 213, in resolve
    return dict[key]
KeyError: '__exception__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ahalev/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1765, in do_it
    var_obj = pydevd_vars.getVariable(self.thread_id, self.frame_id, scope, attrs)
  File "/home/ahalev/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 240, in getVariable
    var = resolver.resolve(var, k)
  File "/home/ahalev/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 215, in resolve
    return getattr(dict, key)
AttributeError: 'dict' object has no attribute '__exception__'
```

I guess this is why the original `__getattr__` is written the way that it is, but it seems a little hack-y to me. Maybe even changing `__getattr__` to 

```python
    def __getattr__(self, name):
        if name.startswith("__"): # this allows for deepcopy
            raise AttributeError(
                "attempted to get missing private attribute '{}'".format(name)
            )
        return getattr(self.env, name)
```
would be better.

**Comment by qstanczyk** [comment] 2021-12-10 17:49
Yeah, I think we can give your suggestion a try. Thanks

**Closed** 2021-12-21 10:03 UTC
