### ISSUE TITLE
Actor/Evaluator keep running when learner dies

### ISSUE THREAD

**Issue by wcarvalho** [deepmind/acme#213] opened 2022-03-30 01:44 UTC
Hello, when the learner dies, the actor and evaluator will keep running. Is there a way to force the full launch pad program to stop if there's an exception in one program?

**Comment by tomdps** [comment] 2022-03-31 13:22
I have the same issue in the distributed layout where the learner thread sometimes hangs and never restarts, for no apparent reason. It's also very inconsistent and hard to reproduce as it happens randomly every 5 or 10 runs in my case, even with the same algorithm, environment, hyperparameters and seed.

There should be a way to automatically kill the run when this happens. A fix for this problem would be even better, but if this comes from launchpad being still under development, I can understand it can be difficult to find an easy fix. Killing the run would at least allow us to not consistently monitor jobs that are running in case hanging of the learner happens.

**Comment by qstanczyk** [comment] 2022-04-01 08:37
Thanks guys for initiating this thread. I think it would be best to avoid crashes in the first place, as otherwise trying to address crashes in an automatic way can lead to problems (lost progress upon forceful restart, ending in an infinite loop in case of crashes happening exactly at step N, problems with monitoring of agent's speed / progress if it keeps restarting periodically). Hence I don't think we should investigate solutions for auto-restarting in case of failures, but address the failures.

**Comment by wookayin** [comment] 2022-04-01 22:25
> I think it would be best to avoid crashes in the first place

Well? In practice how can one avoid this? I don't think anyone in the world can write a code that is always bug-free. In real life, anything can go wrong unexpectedly and anytime; that would be why exceptions exist.

I believe [fail-fast](https://en.wikipedia.org/wiki/Fail-fast) is an important principle; rather than restarting

One hypothetical solution would be to install an exception handler (`sys.excepthook`) for all launchpad process such that in case of uncaught exception, it requests launchpad to terminate the entire runtime and report the error. I think launchpad is responsible for doing this *by default*.

**Comment by qstanczyk** [comment] 2022-04-04 10:50
Depending on the execution mode Launchpad "reports" failures of nodes in a different way:
- For multi threaded execution raised exception in one of the nodes (threads) should result in termination of the program.
- In case of mulit-process execution a node that crashed also stops (starting from [this change](https://github.com/deepmind/launchpad/commit/f21d7985443c748fd4c99ee4ce4894ea0ee359dd) the node that crashes goes into post-mortem mode, so that it is possible to debug its state (note this change was just submitted, so you will have to use nightly release). I find one of the window sessions (or tmux) easiest to use this post-mortem session.

I hope you find the above useful. Any suggestions are welcome.

**Comment by tomdps** [comment] 2022-04-06 08:17
In my case, I use multi-threading with the basic distributed layout. The issue is that no exception is actually raised even with the maximum level of verbosity. What seems to happen is that the learner node "hangs" silently at some point randomly and the .run method of the node stops being executed / is "paused", as if a .sleep() with infinite time was triggered. 

Because there is no exception, the rest of the run continues smoothly but since I control the sampletoinsert amount, the collection process also stops, and the evaluator then starts collecting infinite amount of experience. Because the rate limiter only watches actor steps to kill the runtime, the run goes on forever.

Again, this happens between 1/5 to 1/20 runs in my case, so it's not that bad but a fix, or insights on the optimal use of multithreading within launchpad to avoid this problem would be greatly appreciated.

**Comment by qstanczyk** [comment] 2022-04-06 08:27
In that case it is hard to expect from Launchpad to detect this kind of an issue, as from the black-box perspective it is not possible to tell whether this is expected behaviour or not. I guess what you could try doing to detect this automatically is for example to introduce a background node / task which checks CPU usage of the computer.

**Comment by qstanczyk** [comment] 2022-05-23 13:20
Please reopen if there are some other related points you would like to discuss.

**Closed by qstanczyk** 2022-05-23 13:20 UTC
