### ISSUE TITLE
Some comments and feedback on recently open sourced JAX agents

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/acme#156] opened 2021-10-08 12:41 UTC
Hi,

This is a follow-up issue after https://github.com/deepmind/acme/issues/149. I am really glad to see these agents available OS in Acme, the implementations are clean and straightforward and match the maths closely. I am sure that researchers in the OS community would benefit immensely from having these baselines available.

Having walked through the implementations, if I may offer a few suggestions about the existing implementation, these points come from our attempts to use Acme extensively in our research in offline RL and transfer learning in RL. 

## Some deviations from standard reference implementations.
*Lack of exploration phase* It's typical for TD3 agents to perform an exploration phase where actions were sampled uniformly from the action spec (e.g. in the reference implementation in https://github.com/sfujim/TD3/blob/master/main.py the author ran 25e3 steps by sampling from the uniform distribution). I couldn't find this behavior in the reference TD3 baseline. Would the author comment on if there could be a performance difference for not using the uniform distribution to fill the replay buffer at the start of training? I expect that things would not differ much if the exploration noise is chosen sensibly and the network is initialized properly, but having some solid benchmark result to back up this would be useful. 

## Some comments on logging and interfaces
I found the GenericActorLearner and Layouts abstraction to be a very nice pattern for creating novel agents from existing algorithms. Having tried to implement these interfaces to write new agents. Here are some changes I wish that can be made in the Acme repository to make writing third-party agents easier.

1. *Support passing in a logger in `builder.make_learner`* https://github.com/deepmind/acme/blob/master/acme/agents/jax/builders.py the builder does not allow a logger to be passed. Supporting custom logger is implemented by the agents by passing a logger_fn in the concrete subclasses (e.g., in value_dice, td3, sac). I feel that we should add an additional logger parameter to the make_learner function to support more diverse use cases. This would also simplify some of the concrete builder implementations by not having to pass a logger_fn.
2. *Single process agent based on LocalLayout should support passing a custom logger*. This follows from the points made above. In general, we would hope to support a custom logger in our experiments. However, some of the baseline agents do not support this. e.g., SAC https://github.com/deepmind/acme/blob/master/acme/agents/jax/sac/agents.py#L93, TD3, and ValueDICE. I suggest that the base local layout supports passing an optional logger.

While in principle we can fork the agents and fix these issues in our forked implementations, it becomes a significant burden when we would like to compare a suite of agents in our custom setting as that would require us to fork and customize all agents. Therefore, I believe the proposed changes are generally useful and would enable more OS users to adopt Acme for their research.

I understand that some of these changes would be difficult to make since it requires repo-wide changes and may potentially affect some of the internal agent implementations. Nevertheless, I hope some of these suggestions may be considered if possible. I am happy to contribute some PRs to make these improvements, but I do understand that this alone would not be sufficient since it would also require someone from DeepMind to migrate the internal implementations.

Best,
Yicheng

**Comment by nikolamomchev** [comment] 2021-10-08 13:09
Thanks for your feeback, Yicheng!

We've already had several discussions on how to pass Loggers around and we are still not convinced we got it right, so your feedback is very useful. I'll discuss this with the team soon.

**Comment by ddsh** [comment] 2021-11-26 17:13
Hi Yicheng, thanks for the feedback.

We did try the random exploration phase. Out of the five following environments: Humanoid-v2, Ant-v2, HalfCheetah-v2, Hopper-v2 and Walker2d-v2, it only provided a slight improvement for HalfCheetah (and with a number of transitions closer to 5k rather than 25k). We do not plan to add this at the moment.

**Comment by ethanluoyc** [comment] 2021-11-26 17:17
Thanks for confirming this. I think it would be best not to include it as it complicates the implementation quite a bit. I did a bit of testing and it seems the initial policy and uniform policy has comparable performance in terms of return, so as far as the standard tasks are concerned I suspect the difference is minimal.

**Comment by nikolamomchev** [comment] 2021-11-26 19:57
Duplicate of #171 and #172

**Closed by nikolamomchev** 2021-11-26 19:57 UTC
